// source/domain/training/training-session.test.mjs — Version 1.1
import test from "node:test";import assert from "node:assert/strict";import {createTrainingSession} from "./training-session.js";
const valid={id:"11111111-1111-4111-8111-111111111111",date:"2026-10-10",activityType:"strength",status:"completed",intensity:"moderate",durationMinutes:45,notes:" upper ",exercises:[{id:"e1",name:"Bench press",muscleGroups:["chest","triceps","chest"],sets:[{reps:10,completed:true,resistance:{value:40,unit:"kg"}},{reps:8,completed:false}]}],createdAt:100,updatedAt:100};
test("normalizes and freezes the session",()=>{const s=createTrainingSession(valid);assert.equal(s.id,valid.id);assert.deepEqual(s.exercises[0].muscleGroups,["chest","triceps"]);assert.equal(s.notes,"upper");assert.equal(Object.isFrozen(s.exercises[0].sets[0]),true);});
test("requires a canonical UUID for session identity",()=>{assert.throws(()=>createTrainingSession({...valid,id:"session-1"}),/id must be a canonical UUID/);assert.equal(createTrainingSession({...valid,id:valid.id.toUpperCase()}).id,valid.id);});
test("rejects impossible calendar dates",()=>assert.throws(()=>createTrainingSession({...valid,date:"2026-02-30"}),/valid ISO calendar date/));
test("requires explicit status and intensity",()=>{assert.throws(()=>createTrainingSession({...valid,status:undefined}),/status is invalid/);assert.throws(()=>createTrainingSession({...valid,intensity:undefined}),/intensity must be explicit/);});
test("requires exercise records for completed strength",()=>assert.throws(()=>createTrainingSession({...valid,exercises:[]}),/requires exercise records/));
test("requires explicit set completion",()=>assert.throws(()=>createTrainingSession({...valid,exercises:[{...valid.exercises[0],sets:[{reps:10}]}]}),/completion must be explicit/));
test("rejects invalid reps and resistance",()=>{assert.throws(()=>createTrainingSession({...valid,exercises:[{...valid.exercises[0],sets:[{reps:-1,completed:true}]}]}),/reps must be/);assert.throws(()=>createTrainingSession({...valid,exercises:[{...valid.exercises[0],sets:[{reps:5,completed:true,resistance:{value:-2,unit:"kg"}}]}]}),/resistance must be non-negative/);});
test("bodyweight does not invent a numeric load",()=>{const s=createTrainingSession({...valid,exercises:[{...valid.exercises[0],sets:[{reps:8,completed:true,resistance:{value:null,unit:"bodyweight"}}]}]});assert.deepEqual(s.exercises[0].sets[0].resistance,{value:null,unit:"bodyweight"});});
test("rejects reversed timestamps",()=>assert.throws(()=>createTrainingSession({...valid,createdAt:200,updatedAt:100}),/valid createdAt and updatedAt/));
